version: "3.7"

volumes:
  postgres:

networks:
  localhost:
    name: localhost

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: postgres
    user: root
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=identity,apps
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - localhost

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    user: root
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
    networks:
      - localhost
